전체 앱 생성, Models.py 작성
wecode-bootcamp-korea/23-1st-TangoPlate-backend pull request #1
Opened 2021-08-03 08:11 UTC by lunayyko

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-전체 앱 생성, Models.py 작성
		 
## 수정 사항들 자세한 내용
- users, restaurants, coupons, reviews 앱 생성
- users           : User, Rating, WishList 모델
- restaurants : Restaurant, Menu, Location, Category, ServingPrice 모델
- coupons      : Coupon, CouponImages 모델
- reviews       :  Review, ReviewImage 모델

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-03 09:33 UTC, kst6294 requested changes
피드백 확인해주시고, 한 코드의 피드백은 작성하신 모든 코드에 해당합니다.
전체적으로 파악해주세요.
그리고 on_delete= 옵션에서 models.CASCADE 외에도 다른 기능도 같이 봐보시면 좋겠습니다.

2021-08-03 09:33 UTC, kst6294 commented on coupons/models.py
> +    price          = models.DecimalField(max_digits= 6, decimal_places=0)
```suggestion
    price          = models.DecimalField(max_digits= 6, decimal_places=1)
```

2021-08-03 09:33 UTC, kst6294 commented on coupons/models.py
> +    restaurants_id = models.ForeignKey('Restaurant', on_delete=models.CASCADE, db_column='restaurants_id')
restaurants_id 로 작성하고, db_column 을 통해 column 을 명시하셨네요!  혹시 column 을 restaurants_id 로 지정한 이유가 따로 있을까요? 그리고 restaurants_id 보다는 restaurant_id 가 더 적절해보입니다. 한 식당에만 존재하는 쿠폰이기 때문이지요.

2021-08-03 09:33 UTC, kst6294 commented on restaurants/models.py
> +    kind = models.CharField(max_length=45)
kind 보다는 name 어떤가요?

2021-08-03 09:33 UTC, kst6294 commented on restaurants/models.py
> +    price = models.CharField(max_length=45)
현재와 같이 price 라는 column인 경우, 3000, 4000 과 같은 숫자가 기대됩니다. 
적절히 수정해주세요.

2021-08-03 09:33 UTC, kst6294 commented on reviews/models.py
> +from restaurants.models import Restaurant
- python
- django
- 사용자 

공백으로 구분해주세요.

2021-08-03 09:33 UTC, kst6294 commented on reviews/models.py
> +    image         = models.CharField(max_length=500)
image 는 url 의 형태로 저장됩니다.

2021-08-03 09:33 UTC, kst6294 commented on reviews/models.py
> +    desc           = models.CharField(max_length=500, null=True)
column, 변수에는  줄임말의 사용은 지양해주세요.

2021-08-03 11:20 UTC, lunayyko commented on restaurants/models.py
> +    kind = models.CharField(max_length=45)
한식 양식 중식 일식인데 category.name이 되니까 괜찮네요!

2021-08-03 11:27 UTC, lunayyko commented
> 그리고 on_delete= 옵션에서 models.CASCADE 외에도 다른 기능도 같이 봐보시면 좋겠습니다.

on_delete=SET_NULL사용해서 참조키가 없어졌을 때 행이 없어지는 것을 예방했습니다

2021-08-04 01:20 UTC, kst6294 requested changes
1. 마이그레이션 해주세요!
2. 피드백에 대해 답변 달아주세요!
3. 현재 외래키로 연결되어 있는 column 이 모두 복수형태로 되어 있네요. 그 이유가 있을까요? 예: categorys_id

2021-08-04 01:20 UTC, kst6294 commented on coupons/models.py
> +    end_date       = models.DateField()
컨벤션 맞춰주세요~!

2021-08-04 01:20 UTC, kst6294 commented on coupons/models.py
> +    restaurant_id = models.ForeignKey('Restaurant', on_delete=models.SET_NULL, db_column='restaurant_id', null=True)
restaurant column 과 db_column 으로 지정된 column 이 동일하기 떄문에 굳이 db_column='restaurant_id' 를 명시하지 않아도 괜찮을 것 같습니다. 어떻게 생각하시나요?
```suggestion
    restaurant = models.ForeignKey('Restaurant', on_delete=models.SET_NULL, null=True)
```

2021-08-04 01:20 UTC, kst6294 commented on coupons/models.py
> +        db_table = 'coupons_images'
```suggestion
        db_table = 'coupon_images'
```

2021-08-04 01:22 UTC, lunayyko commented on coupons/models.py
> +    restaurant_id = models.ForeignKey('Restaurant', on_delete=models.SET_NULL, db_column='restaurant_id', null=True)
통일하려고 다 붙였는데 없어도 될 것 같습니다 !

2021-08-04 01:23 UTC, lunayyko commented on reviews/models.py
> +    image         = models.CharField(max_length=500)
url필드로 변경했습니다

2021-08-04 01:23 UTC, lunayyko commented on reviews/models.py
> +    desc           = models.CharField(max_length=500, null=True)
넵 description으로 변경했습니다

2021-08-04 01:25 UTC, lunayyko commented
> 3. 현재 외래키로 연결되어 있는 column 이 모두 복수형태로 되어 있네요. 그 이유가 있을까요? 예: categorys_id
ERD짤때 테이블 이름 뒤에 id를 붙인다고 생각해서 복수로 썼는데 생각해보니까 행 한 개에 아이디가 붙는거니까 단수가 맞겠네요 고치겠습니다

2021-08-04 01:25 UTC, lunayyko commented on restaurants/models.py
> +    price = models.CharField(max_length=45)
PositiveIntField로 수정했습니다

2021-08-04 01:26 UTC, lunayyko commented on reviews/models.py
> +from restaurants.models import Restaurant
넵

2021-08-04 04:26 UTC, lunayyko commented on coupons/models.py
> +    end_date       = models.DateField()
넵

2021-08-04 04:28 UTC, Samdaso-o commented on coupons/models.py
> +    price          = models.DecimalField(max_digits= 6, decimal_places=0)
수정완료했습니다!

2021-08-04 04:28 UTC, Samdaso-o commented on coupons/models.py
> +    restaurants_id = models.ForeignKey('Restaurant', on_delete=models.CASCADE, db_column='restaurants_id')
넵 !!

2021-08-04 04:28 UTC, Samdaso-o commented on coupons/models.py
> +        db_table = 'coupons_images'
넵 ㅎㅎ

2021-08-04 04:41 UTC, kst6294 requested changes
마이그레이션 해주세요~!

2021-08-04 05:01 UTC, Samdaso-o commented
헉... 마이그레이션 하겟습니다... 죄송합니다 ㅠㅠ

2021-08-04 05:14 UTC, lunayyko commented
마이그레이션 했습니다!

2021-08-04 06:21 UTC, kst6294 approved these changes
LGTM 👍

2021-08-04 06:21 UTC, merged