ADD:위시리스트 모달창 뷰 작성
wecode-bootcamp-korea/23-1st-TangoPlate-backend pull request #10
Opened 2021-08-11 04:27 UTC by Samdaso-o

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 화면페이지마다 모달로 존재하는 가고싶다 페이지 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-11 06:33 UTC, Kang-kyunghun requested changes

2021-08-11 06:33 UTC, Kang-kyunghun commented on users/views.py
> +            return JsonResponse({'MESSAGE':'NONE'}, status = 200)
좋아요 listdp 데이터가 없을 때 에러 메시지를 보내는 것이 아닌 빈 list를 보내주시면 됩니다.

2021-08-11 06:33 UTC, Kang-kyunghun commented on users/views.py
> +            restaurants = Restaurant.objects.filter(id=wish.restaurant_id)
wishlist table에 이미 product가 연결 되어있을 것 같은데, wishlist 정보로부터 product를 가져와 보세요.

2021-08-11 06:33 UTC, Kang-kyunghun commented on users/views.py
> +                )
1. review에 대한 값이 빠져 있네요. 확인해 주세요.
2. list comprehension으로 바꿔 보세요.

2021-08-11 06:45 UTC, Samdaso-o commented on users/views.py
> +            return JsonResponse({'MESSAGE':'NONE'}, status = 200)
오호! 넵 ㅎ

2021-08-11 06:45 UTC, Samdaso-o commented on users/views.py
> +            restaurants = Restaurant.objects.filter(id=wish.restaurant_id)
넵 !

2021-08-11 07:11 UTC, Samdaso-o commented on users/views.py
> +                )
앗! 리뷰는 제외하도록 하겠습니다 ㅎ
wish.restaurant.review_set.filter(restaurant_id=wish.restaurant.id)[0].reviewimage_set.last().image 코드로
한번에 접근해보았습니다.

2021-08-11 10:59 UTC, lordmyshepherd requested changes

2021-08-11 10:59 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'MESSAGE':results}, status = 200)
```suggestion
            return JsonResponse({'MESSAGE':results}, status = 404)
```

2021-08-11 10:59 UTC, lordmyshepherd commented on users/views.py
> +            )
for문을 list comphrehension 표현식으로 수정해보세요~

2021-08-11 11:38 UTC, Samdaso-o commented on users/views.py
> +            return JsonResponse({'MESSAGE':results}, status = 200)
넵 ㅎㅎ

2021-08-11 11:38 UTC, Samdaso-o commented on users/views.py
> +            )
넵 수정하겟습니다 ㅎ

2021-08-12 01:53 UTC, kst6294 approved these changes
conflict 해결해주세요!

2021-08-12 01:58 UTC, Samdaso-o commented
넵 수정했습니다 ㅎ

2021-08-12 02:02 UTC, merged