[23기 고유영] ADD: 가고싶다(좋아요) 뷰
wecode-bootcamp-korea/23-1st-TangoPlate-backend pull request #11
Opened 2021-08-11 05:05 UTC by lunayyko

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 가고싶다 뷰 추가
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-11 09:35 UTC, lordmyshepherd requested changes

2021-08-11 09:35 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
1.` wish_list 추가` -> post handler method에 구현, `wish_list 삭제` -> delete handler method 안에 구현하기.
2. KeyError가 발생할 수 있는 케이스가 없습니다.
```python
a = {"name" : "google"}
a["nam"]
a.get("nam", 1)
>> None
```
3. ` User.objects.get(id = request.user.id)` 호출했을 때, matching되는 데이터가 없는 경우 어떤 에러를 발생하나요?
어떤 `except XXXXXX`:를  해줘야하나요?

2021-08-11 10:03 UTC, lunayyko commented on users/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
ObjectDoesNotExist 써야겠네요! 추가했습니다

2021-08-12 01:58 UTC, kst6294 requested changes

2021-08-12 01:58 UTC, kst6294 commented on users/views.py
> +            return JsonResponse({'result' : result}, status=200)
어떠한 동작을 수행하나요?
통신결과도 같이 올려주세요.

2021-08-12 02:07 UTC, lunayyko commented on users/views.py
> +            return JsonResponse({'result' : result}, status=200)
올렸습니다~

2021-08-12 04:45 UTC, kst6294 requested changes

2021-08-12 04:45 UTC, kst6294 commented on users/views.py
> +            return JsonResponse({'result' : result}, status=200)
is_wished, true , false 를 return 하는 이유가 있나요?
상태코드로 관리하면 안되려나요?

2021-08-12 04:53 UTC, lunayyko commented on users/views.py
> +            return JsonResponse({'result' : result}, status=200)
가고싶다 클릭했을 때 바뀌는 값을 프론트에 보내드리려고 넣었는데 프론트하고 상의해보고 뺄 수 있으면 빼도록 하겠습니다~!

2021-08-12 05:46 UTC, lunayyko commented on users/views.py
> +            return JsonResponse({'result' : result}, status=200)
위시 코드가 작동이 안 되는데 도와주실 수 있을까요?!

2021-08-12 06:54 UTC, lunayyko commented on users/views.py
> +            return JsonResponse({'result' : result}, status=200)
상태코드로 관리하는걸로 바꿔서 푸시했습니다!

2021-08-12 08:13 UTC, redsaumon commented
수고하셨습니다!!:+1:

2021-08-12 08:13 UTC, merged