ADD : 회원가입/로그인 View 작성
wecode-bootcamp-korea/23-1st-TangoPlate-backend pull request #2
Opened 2021-08-04 07:45 UTC by Samdaso-o

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-04 07:46 UTC, Samdaso-o commented
<img width="1305" alt="스크린샷 2021-08-04 오후 4 38 47" src="https://user-images.githubusercontent.com/76812640/128142335-2d5dfa85-3aa1-4d37-95dd-3e93921c5077.png">
<img width="1292" alt="스크린샷 2021-08-04 오후 4 41 14" src="https://user-images.githubusercontent.com/76812640/128142340-75b12a8e-c550-4aab-b104-70aa3ba49b00.png">

2021-08-05 02:32 UTC, kst6294 requested changes
확인바랍니다~!

2021-08-05 02:32 UTC, kst6294 commented on users/utils.py
> +import jwt
데코레이터에 해당하는 기능은 따로 PR 올려주세요~!

2021-08-05 02:32 UTC, kst6294 commented on users/utils.py
> +            user     = jwt.decode(token, SECRET_KEY, algorithms='HS256')
알고리즘은 my_settings.py 에 추가해서 사용해주세요~

2021-08-05 02:32 UTC, kst6294 commented on users/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_VALUE'}, status = 401)
이 코드는 어떠한 기능을 수행하나요?

2021-08-05 02:32 UTC, kst6294 commented on users/views.py
> +            if data['email'] == "" or data['password'] == "":
data['email'] 을 자주 사용하기 때문에, 변수에 담아서 사용해주세요~

```suggestion
    email = data['email']
```

2021-08-05 04:30 UTC, Samdaso-o commented on users/views.py
> +            if data['email'] == "" or data['password'] == "":
넵 ㅎㅎ 수정하겟습니다

2021-08-05 04:31 UTC, Samdaso-o commented on users/utils.py
> +            user     = jwt.decode(token, SECRET_KEY, algorithms='HS256')
넵 !

2021-08-05 04:35 UTC, Samdaso-o commented on users/utils.py
> +import jwt
넵! 로그인 및 회원가입 기능 구현완료 후 PR하도록 하겟습니다!

2021-08-05 04:35 UTC, Samdaso-o commented on users/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_VALUE'}, status = 401)
생각해보니 keyerror 부분과 겹치는 것 같아 삭제하였습니다...ㅎㅎ

2021-08-05 04:56 UTC, Samdaso-o reviewed
- 로그인 성공시 email과 nickname을 같이 담아달라는 프론트의 요청으로 SignInView 코드 수정

2021-08-05 05:03 UTC, kst6294 requested changes
확인바랍니다!

2021-08-05 05:03 UTC, kst6294 commented on users/views.py
> +#from users.utils         import login_decorator
주석은 제거해주세요~

2021-08-05 05:03 UTC, kst6294 commented on users/views.py
> +from my_settings          import SECRET_KEY, algorithm
algorithm 은 상수로 처리해주세요!

2021-08-05 05:03 UTC, kst6294 commented on users/views.py
> +from restaurants.models   import Restaurant as RestaurantModel
User 클래스나 UserModel 둘이 크게 차이가 없어보입니다.
User -> UserModel 로 변경해서 사용하는 것에 크게 메리트가 없어보입니다.
4글자로 가능한 것을 굳이 9자로 늘리는 상황같네요.

2021-08-05 05:03 UTC, kst6294 commented on users/views.py
> +                )
반복문을 사용하지 않는 상황에서 굳이 append 메소드를 사용하지 않아도 괜찮을 것 같습니다. 바로 result 라는 리스트 안에 선언해주세요.
여러개의 값을 담는 다는 의미의 results 보다는 result 가 더 적절해보입니다.

2021-08-05 05:09 UTC, Samdaso-o commented on users/views.py
> +#from users.utils         import login_decorator
넵 제거하도록 하겠습니다.

2021-08-05 05:13 UTC, Samdaso-o commented on users/views.py
> +from restaurants.models   import Restaurant as RestaurantModel
아.. 생각해보니 그렇네요.. 감사합니다

2021-08-05 05:24 UTC, Samdaso-o commented on users/views.py
> +from my_settings          import SECRET_KEY, algorithm
넵 ㅎ

2021-08-05 05:24 UTC, Samdaso-o commented on users/views.py
> +                )
앗! 넵 ㅎㅎ

2021-08-05 06:42 UTC, Samdaso-o commented
프론트에서 Response 값의 배열을 좀 더 가볍게 수정 요청하여, 리스트를 제외하고 값을 바로 반환하도록 변경

2021-08-05 07:10 UTC, kst6294 approved these changes
LGTM 👍

2021-08-05 07:10 UTC, merged