EDIT:reviews.view 작성 / post, put, delete
wecode-bootcamp-korea/23-1st-TangoPlate-backend pull request #3
Opened 2021-08-05 12:52 UTC by Samdaso-o

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

<img width="1272" alt="스크린샷 2021-08-05 오후 9 45 56" src="https://user-images.githubusercontent.com/76812640/128352974-55edf9f2-f69d-42ef-9cf7-25113d24e123.png">
<img width="1272" alt="스크린샷 2021-08-05 오후 9 46 29" src="https://user-images.githubusercontent.com/76812640/128352992-8a563ae4-5bd9-42ef-ab17-6f7754ab313d.png">
<img width="1272" alt="스크린샷 2021-08-05 오후 9 46 54" src="https://user-images.githubusercontent.com/76812640/128352998-8c829f18-ff99-42ea-ba67-e36fc9b30862.png">

2021-08-06 01:38 UTC, kst6294 requested changes
전체적으로 확인바랍니다.

2021-08-06 01:38 UTC, kst6294 commented on reviews/urls.py
> +    path('/<int:restaurant_id>', Review_View.as_view()),
push 하기 전에 코드 전체적으로 꼭 확인해주세요~!

2021-08-06 01:38 UTC, kst6294 commented on reviews/views.py
> +# Create your views here.
주석 제거해주세요!

2021-08-06 01:38 UTC, kst6294 commented on reviews/views.py
> +                    return JsonResponse({'MESSAGE':'EXISTS'}, status=400)
user_id 뿐만 아니라 restaurant_id 도 포함해서 filter 메소드를 사용할 수 있습니다.
그 이후 exsits 메소드에 대해 알아보시면 좋겠습니다.

2021-08-06 01:38 UTC, kst6294 commented on reviews/views.py
> +                user_id       = User.objects.get(id=user.id).id,
이미 request.user 를 통해 user 객체를 전달받았습니다.

2021-08-06 01:38 UTC, kst6294 commented on reviews/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
위의 피드백을 전체적으로 반영해주세요!

2021-08-06 01:38 UTC, kst6294 commented on reviews/views.py
> +            review_object = Review.objects.get(user_id = user.id, restaurant_id=restaurant_id)
해당하는 Review 모델이 없는 경우 어떻게 되나요?

2021-08-06 01:38 UTC, kst6294 commented on reviews/views.py
> +            rating_object = Rating.objects.get(user_id = user.id, restaurant_id=restaurant_id)
해당하는 Rating 모델이 없는 경우 어떻게 되나요?

2021-08-06 01:38 UTC, kst6294 commented on reviews/views.py
> +            review_id = user_review[0].id
```suggestion
            review = Review.objects.filter(user_id = user.id, restaurant_id = restaurant_id)
            review.update(
                    restaurant_id = restaurant_id,
                    user_id       = User.objects.get(id=user.id).id,
                    description   = data['description'],
                    )
```

이런식으로 작성할 경우, 아래에서도 filter 를 통한 반환값을 재 사용할 수 있습니다.
추가적으로 filter 한 후에 반환되는 객체가 있는지 검증해주세요. 그리고 user_review[0] 와 같이 인덱싱 할 경우, 해당하는 객체가 없을 때 어떤 에러가 발생하는지 확인해주세요.

2021-08-06 04:30 UTC, Samdaso-o commented on reviews/urls.py
> +    path('/<int:restaurant_id>', Review_View.as_view()),
넵 ㅠ 죄송합니다

2021-08-06 04:31 UTC, Samdaso-o commented on reviews/views.py
> +# Create your views here.
넵 !

2021-08-06 04:35 UTC, Samdaso-o commented on reviews/views.py
> +                    return JsonResponse({'MESSAGE':'EXISTS'}, status=400)
넵 ㅎㅎ

2021-08-06 04:35 UTC, Samdaso-o commented on reviews/views.py
> +                user_id       = User.objects.get(id=user.id).id,
앗!! 넵 ㅎ

2021-08-06 04:36 UTC, Samdaso-o commented on reviews/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
넵 감사합니다 ㅠㅠ

2021-08-06 04:52 UTC, Samdaso-o commented on reviews/views.py
> +            review_object = Review.objects.get(user_id = user.id, restaurant_id=restaurant_id)
함수를 시작하자마자 객체가 존재여부를 확인하는 조건문을 추가하도록 하겠습니다.

2021-08-06 04:54 UTC, Samdaso-o commented on reviews/views.py
> +            rating_object = Rating.objects.get(user_id = user.id, restaurant_id=restaurant_id)
위에서 적용한 조건문으로 처리 가능할 듯 싶습니다. 
리뷰 작성 시 rating을 받지 않으면 에러가 발생 하므로 리뷰가 존재할시, rating 모델이 존재할 것으로 생각됩니다.

2021-08-06 05:12 UTC, Samdaso-o commented on reviews/views.py
> +            review_id = user_review[0].id
아... 반환값 재사용을 생각을 하지 못했습니다 ㅠㅠ 객체가 존재하지 않으면 작동하지 않는 다는 조건문을 추가하도록 하겠습니다.

2021-08-09 02:27 UTC, Samdaso-o commented
Q객체 사용해보았습니다

2021-08-09 02:49 UTC, kst6294 reviewed
restful api 먼저 확인해주세요!

2021-08-09 02:49 UTC, kst6294 commented on .gitignore
> +utils.py
utils.py 를 gitignore 에 추가한 이유가 있나요?

2021-08-09 02:49 UTC, kst6294 commented on reviews/views.py
> +class Review_View(View):
컨벤션에 맞추어 class 이름 작성해주세요~!

2021-08-09 02:49 UTC, kst6294 commented on reviews/urls.py
> +from reviews.views import Review_View
정리해주세요~!

2021-08-09 02:49 UTC, kst6294 commented on reviews/views.py
> +                return JsonResponse({'MESSAGE':'EXISTS'}, status=400)
message 가 약간 불분명 한것 같아요.

2021-08-09 02:49 UTC, kst6294 commented on reviews/views.py
> +            review_id = Review.objects.get(user_id= user.id, restaurant_id=restaurant_id)
```suggestion
            review = Review.objects.create(
                restaurant_id = restaurant_id,
                user_id       = user.id,
                description   = data['description'],
            )

```

2021-08-09 02:49 UTC, kst6294 commented on reviews/views.py
> +                review_id = review_id.id,
```suggestion
                review_id = review.id,
```

2021-08-09 02:49 UTC, kst6294 commented on reviews/views.py
> +                review_id = review_id.id,
위의 피드백과 같이 반영되어야 합니다.

2021-08-09 02:49 UTC, kst6294 commented on reviews/urls.py
> +    path('/<int:restaurant_id>', Review_View.as_view()),
reviews/1 

처럼 되네요.

restful api 복습하시고 다시 반영해주세요.

2021-08-09 02:49 UTC, kst6294 commented on reviews/views.py
> +    def delete(self, request, restaurant_id):
위의 피드백부터 반영해주세요.

2021-08-09 02:54 UTC, Samdaso-o commented on .gitignore
> +utils.py
로그인 관련 데코레이터라 숨기는 것이 좋을 꺼 같아 추가했었습니다...ㅎ
제거하도록 하겟습니다 ㅎㅎ

2021-08-09 02:54 UTC, Samdaso-o commented on reviews/views.py
> +class Review_View(View):
넵 !

2021-08-09 02:55 UTC, Samdaso-o commented on reviews/urls.py
> +from reviews.views import Review_View
넵 !

2021-08-09 02:56 UTC, Samdaso-o commented on reviews/views.py
> +                return JsonResponse({'MESSAGE':'EXISTS'}, status=400)
넵 변경하도록 하겟습니다 ㅎ

2021-08-09 06:11 UTC, Samdaso-o commented on reviews/views.py
> +                review_id = review_id.id,
넵 !

2021-08-09 11:49 UTC, Samdaso-o commented on reviews/views.py
> +    def delete(self, request, restaurant_id):
넵 피드백 받은 부분 전부 수정완료해 push 했습니다 ^^

2021-08-09 15:21 UTC, kst6294 requested changes

2021-08-09 15:21 UTC, kst6294 commented on reviews/views.py
> +class ReviewCreatView(View):
view 를 분리한 이유가 있나요?

2021-08-09 16:05 UTC, lunayyko commented on reviews/views.py
> +class ReviewCreatView(View):
URI를 다르게 쓰려고 분리했습니다

2021-08-10 00:51 UTC, Samdaso-o commented on reviews/views.py
> +class ReviewCreatView(View):
리뷰를 생성시에는 restaurant/<int:restaurant_id>/review 를 사용,
리뷰를 수정 및 삭제시에는 restaurant/<int:restaurant_id>/review/<int:review_id>를 사용하고자 하여 view를 분리했습니다.

2021-08-10 03:08 UTC, lordmyshepherd requested changes

2021-08-10 03:08 UTC, lordmyshepherd commented on reviews/views.py
> +            if not Review.objects.filter(id=review_id).exists():
line 44 ~ line 45 한 칸 띄워주세요~

2021-08-10 03:08 UTC, lordmyshepherd commented on reviews/views.py
> +class ReviewCreatView(View):
하나의 View class 안에 `get()`, `post()`, `delete()`, `put()` handler method를 구현해주세요. Class형 View의 컨셉에 맞게 ReviewView 객체가 생성, 조회, 삭제, 업데이트 행동을 할 수 있도록 구현해주세요.

```suggestion
class ReviewView(View):
    def get(self, ..): ..
    
    def post(self, ..):
    
    def put(self, ..):
    
    def delete(self, ..):
    
```

2021-08-10 04:28 UTC, Samdaso-o commented on reviews/views.py
> +class ReviewCreatView(View):
넵

2021-08-10 04:28 UTC, Samdaso-o commented on reviews/views.py
> +            if not Review.objects.filter(id=review_id).exists():
넵

2021-08-11 01:35 UTC, lordmyshepherd requested changes

2021-08-11 01:35 UTC, lordmyshepherd commented on reviews/views.py
> +            )
잘 합쳐주셨네요!! 👍 

여기서 고려해야되는 두 가지만 더 고려하면 더 좋은 코드가 될 것 같습니다.
1. db에서 review를 조회할 때, user_id도 함께 조회한다. --> review_id로만 조회하면 누구든지 인증만 되면 어떤 리뷰도 업데이트할 수 있는 디버깅하기 힘든 오류가 발생할 수 있다.
2. line 50~ 53 로직은 예를들어 `review_id=1`에 해당하는 모든 image를 업데이트해버리는 오류가 있습니다.

두가지를 고려해서 코드를 수정해주세요!

```suggestion
        review = Review.objects.get(id=review_id, user_id=user.id)
        review.description = data['description']
        review.rating = data['rating']

        Review.objects.filter(id=review_id).update(
                restaurant_id = restaurant_id,
                user_id       = user.id,
                description   = data['description'],
                rating        = data['rating'],
                )

        ReviewImage.objects.filter(review_id = review_id).update(
            review_id = review_id,
            image     = data['image'],
            )
```

2021-08-11 04:35 UTC, Samdaso-o commented on reviews/views.py
> +            )
아하! 그렇군요 ㅎㅎ 
그렇다면 filter(id=review_id, user_id=user.id)로 user_id 값도 함께 조회될 수 있도록 변경하겠습니다!

2021-08-11 04:53 UTC, Samdaso-o commented
<img width="1220" alt="스크린샷 2021-08-11 오후 1 52 45" src="https://user-images.githubusercontent.com/76812640/128971514-d51bb17e-92d1-401a-b4df-5f44d43b6dec.png">
<img width="1220" alt="스크린샷 2021-08-11 오후 1 52 21" src="https://user-images.githubusercontent.com/76812640/128971522-b3b9fb1a-8dd2-4f07-942b-b6431b36e04b.png">

수정 후 postman으로 확인작업완료

2021-08-11 10:10 UTC, lordmyshepherd requested changes

2021-08-11 10:10 UTC, lordmyshepherd commented on reviews/views.py
> +        )
승훈님 잘 작성해 주셨네요~ 다만 이 경우에는 `transcation` 개념을 찾아보시고 적용해주시면 좋을 것 같습니다.

2021-08-11 10:10 UTC, lordmyshepherd commented on reviews/views.py
> +        return JsonResponse({"MESSAGE": 'SUCCESS'}, status=204)
`Review.objects.get(id=review_id, user_id=user.id).delete()` 했을 경우에 매칭되는 데이터가 없는 경우에 대한 에러 핸들링이 안되어 있는 것 같습니다! 추가해주시면 좋을 것 같아요~

```suggestion
        user = request.user

        if not Review.objects.filter(id=review_id, user_id=user.id).exists():
            return JsonResponse({'MESSAGE':'NOT_EXISTS'}, status=400)

        Review.objects.get(id=review_id, user_id=user.id).delete()

        return JsonResponse({"MESSAGE": 'SUCCESS'}, status=204)
```

2021-08-11 12:41 UTC, Samdaso-o commented on reviews/views.py
> +        )
넵 ㅎ 덕분에 새로운 개념을 알게되었습니다 ㅎㅎ

2021-08-11 12:43 UTC, Samdaso-o commented on reviews/views.py
> +        return JsonResponse({"MESSAGE": 'SUCCESS'}, status=204)
엇..! 61번부터 있는 if문이 존재여부를 확인하고 삭제를 진행하는 코드로 구성하였습니다..ㅎㅎ

2021-08-12 01:51 UTC, kst6294 approved these changes
LGTM 👍

2021-08-12 01:52 UTC, merged