식당 세부정보 뷰 작성
wecode-bootcamp-korea/23-1st-TangoPlate-backend pull request #5
Opened 2021-08-06 06:50 UTC by lunayyko

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 식당 세부정보 뷰 작성
		 
## 수정 사항들 자세한 내용
- 식당별 별점 aggregate 사용

## 기타 질문 및 특이 사항
- 비회원/회원을 구현하려면 login decorator의 위치를 어떻게 조정해야할까요? (비회원도 화면이 보이지만 가고싶다 혹은 리뷰작성을 클릭하면 알림창 생성

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

![Screen Shot 2021-08-06 at 3 42 18 PM](https://user-images.githubusercontent.com/8315252/128468577-2c518b28-21a5-4d39-b52a-7e2aedd80f75.png)

2021-08-06 09:10 UTC, kst6294 requested changes
확인바랍니다 👍

2021-08-06 09:10 UTC, kst6294 commented on restaurants/urls.py
> +    # path("/restaurant/?no=<int:restaurant_id>", RestaurantDetailView.as_view()),
사용하지 않을 주석은 제거해주세요!

2021-08-06 09:10 UTC, kst6294 commented on restaurants/views.py
> +    @login_decorator
식당에대한 세부 정보는 로그인한 사용자만 확인이 가능한가요?

2021-08-06 09:10 UTC, kst6294 commented on restaurants/views.py
> +            reviews           = Review.objects.filter(restaurant_id = restaurant_id)
review 는 restaurant 와 역참조 관계라면, `_set` 에 대해 알아보시면 좋을것 같습니다.

2021-08-06 09:10 UTC, kst6294 commented on restaurants/views.py
> +            user_rating       = Rating.objects.get(user_id = request.user.id, restaurant_id=restaurant_id)
위의 피드백과 동일합니다.

2021-08-06 09:10 UTC, kst6294 commented on restaurants/views.py
> +            menus             = restaurant.menu_set.filter(restaurant_id=restaurant.id)
여기두요~!

2021-08-06 09:10 UTC, kst6294 commented on restaurants/views.py
> +            is_wished         = restaurant.wishlist_set.filter(restaurant_id=restaurant_id).exists()
여기는 _set 을 사용하셨네요?

2021-08-06 09:10 UTC, kst6294 commented on restaurants/views.py
> +            })
위의 피드백 반영과 list_comprehension 반영해보세요~!

2021-08-06 09:10 UTC, kst6294 commented on reviews/urls.py
> +]
review 에 해당하는 코드는 제거해주세요!

2021-08-06 09:11 UTC, lunayyko commented on restaurants/urls.py
> +    # path("/restaurant/?no=<int:restaurant_id>", RestaurantDetailView.as_view()),
넵

2021-08-06 10:18 UTC, lunayyko commented on restaurants/views.py
> +    @login_decorator
비회원도 식당정보를 볼 수 있어야겠죠 로그인 데코레이터를 삭제했습니다!

2021-08-06 10:19 UTC, lunayyko commented on restaurants/views.py
> +            reviews           = Review.objects.filter(restaurant_id = restaurant_id)
넵 정참조는 그대로 연결하고 역참조는 _set추가했습니다

2021-08-08 08:02 UTC, lunayyko commented on restaurants/views.py
> +    @login_decorator
로그인 데코레이터 삭제하니까 유저아이디 받아서 리뷰의 별점 보여주는 부분이 작동하지 않아서 에러가 납니다. 해당 데이터가 없으면 null을 반환하는 로직을 짜려고하는데 어떻게 검색해야 해당 내용이 나올까요?

2021-08-08 08:03 UTC, lunayyko commented on restaurants/views.py
> +            })
list_comprehension 읽어봤는데 혹시 더 자세하게 어떤 식으로 개선하면 좋을지 알려주실 수 있을까요..?

2021-08-08 08:04 UTC, lunayyko commented on reviews/urls.py
> +]
넵

2021-08-09 01:34 UTC, kst6294 requested changes
확인바랍니다!

2021-08-09 01:34 UTC, kst6294 commented on restaurants/urls.py
> +from .views      import RestaurantDetailView
공백으로 구분해주세요!
- python 
- django
- 사용자

2021-08-09 01:34 UTC, kst6294 commented on restaurants/views.py
> +            reviews            = Review.objects.filter(restaurant_id = restaurant_id)
```suggestion
    # 1안)
            restaurant         = Restaurant.objects.get(id = restaurant_id)
            reviews            = Review.objects.filter(restaurant_id = restaurant_id)
           
    # 2안)
            restaurant         = Restaurant.objects.get(id = restaurant_id)
            restaurant.reviews_set.all()
```

1안과 2안을 테스트해보시고, 어떠한 차이가 있는지 확인해주세요!
이 부분 파악하시면 아래 코드도 동일하게 반영가능합니다!

2021-08-09 06:56 UTC, lunayyko commented on restaurants/views.py
> +            reviews            = Review.objects.filter(restaurant_id = restaurant_id)
2안이 불필요한 주고받음을 줄일 수 있을 것 같습니다~

2021-08-09 09:14 UTC, lunayyko commented
제가 이 브랜치를 feature/restaurant-filter-view에서 머지한 것 같은데 그래서 푸시가 안 되길래 feature/restaurant-detail 브랜치를 새로 만들었는데 이 PR을 닫고 feature/restaurant-detail에서 새 PR을 올려도 될까요?

2021-08-09 16:36 UTC, lunayyko commented on restaurants/urls.py
> +from .views      import RestaurantDetailView
넵

2021-08-11 01:45 UTC, closed without merging