ADD : restaurants_view_search 추가
wecode-bootcamp-korea/23-1st-TangoPlate-backend pull request #6
Opened 2021-08-08 08:19 UTC by Samdaso-o

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 검색기능을 하기 위한 코드 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 입력된 검색어값을 각 칼럼별로 조회해 restaurant 출력

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- Q객체를 쓰면 좋을듯 싶은데, 아이디어가 떠오르지 않습니다...

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-11 02:17 UTC, lordmyshepherd requested changes

2021-08-11 02:17 UTC, lordmyshepherd commented on users/utils.py
> +def login_decorator(func):
search view에 `login_decorator` 코드가 같이 올라온 이유가 있나요?
PR은 하나의 기능에 대한 코드만 올라오도록 만들어주셔야 합니다~

2021-08-11 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +
한 줄 지워주세요~

2021-08-11 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +                restaurants = Restaurant.objects.filter(category_id=category.id)
이부분은 좀 이상하지 않나요?

categories를 순회하면서 restaurants에 매번 새로운 쿼리셋을 할당해주는 이유가 궁굼하네요??

2021-08-11 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +                restaurants = restaurants.union(Restaurant.objects.filter(id=menu.restaurant.id))
union을 잘 사용하셨네요 ㅎㅎ
다면 여기서 for문을 사용하지 않고 가져오는 방법은 없을까요?

2021-08-11 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +            restaurants = restaurants.union(Restaurant.objects.filter(address__contains=search))
여기에는 `exists()`를 사용하지 않으신 이유가 있나요?

2021-08-11 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +        if Restaurant.objects.filter(name__contains=search):
마찬자기지 입니다.

2021-08-11 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +            )
아래와 같이 참조되어 있는 객체의 데이터는 부모 인스턴스로부터 가져올 수 있습니다. 아래와 같이 수정해주세요~

```suggestion
                {
                    "id"          : restaurant.id,
                    "name"        : restaurant.name,
                    "address"     : restaurant.address,
                    "is_wished"   : restaurant.wishlist_set.exists(),
                    "rating"      : reviews.aggregate(Avg('rating')),
                    "review"      : [{
                        "description" : review.description,
                        "images"      : [{"url" : image.url} for image in review.image_set.all()]
                    } for review in restaurant.review_set.all()]
                }
```

2021-08-11 05:02 UTC, Samdaso-o commented on users/utils.py
> +def login_decorator(func):
앗 넵 알겟습니다!

2021-08-11 05:03 UTC, Samdaso-o commented on restaurants/views.py
> +
넵!

2021-08-11 05:06 UTC, Samdaso-o commented on restaurants/views.py
> +            restaurants = restaurants.union(Restaurant.objects.filter(address__contains=search))
앗! 제가 실수한거 같습니다

2021-08-11 05:06 UTC, Samdaso-o commented on restaurants/views.py
> +        if Restaurant.objects.filter(name__contains=search):
넵!

2021-08-11 05:07 UTC, Samdaso-o commented on restaurants/views.py
> +            )
큰 깨달음을 얻고 갑니다...

2021-08-11 05:19 UTC, Samdaso-o commented on restaurants/views.py
> +                restaurants = Restaurant.objects.filter(category_id=category.id)
큰 깨달음을 알았습니다 ㅠㅠ  감사합니다

2021-08-11 05:19 UTC, Samdaso-o commented on restaurants/views.py
> +                restaurants = restaurants.union(Restaurant.objects.filter(id=menu.restaurant.id))
넵!! 수정하였습니다

2021-08-11 10:25 UTC, lordmyshepherd requested changes

2021-08-11 10:25 UTC, lordmyshepherd commented on restaurants/views.py
> +                        "image"       : restaurant.review_set.filter(restaurant_id=restaurant.id)[0].reviewimage_set.last().image,
이부분은 오프라인에서 피드백 드린데로 수정해주세요~

2021-08-11 10:45 UTC, Samdaso-o commented on restaurants/views.py
> +                        "image"       : restaurant.review_set.filter(restaurant_id=restaurant.id)[0].reviewimage_set.last().image,
넵!
그 Model property부분에서 review값이 두개이상이 들어오면 get()을 사용하면 오류가 발생해, filter()로 변경하였습니다.
if문에서 이미 review가 존재하는것을 확인하여서, 인덱싱을 사용해도 무방할듯 싶어 인덱싱으로 하나의 값만 출력되도록 하였습니다!

2021-08-12 02:07 UTC, kst6294 approved these changes
LGTM 👍

2021-08-12 02:08 UTC, Samdaso-o commented
넵 해결했습니다 ㅎ

2021-08-12 04:42 UTC, merged