URI 수정, 필터된 식당리스트뷰 추가, 리뷰 CRUD 유저 판별 로직 추가
wecode-bootcamp-korea/23-1st-TangoPlate-backend pull request #8
Opened 2021-08-09 15:23 UTC by lunayyko

## 수정 사항 간략한 한줄 요약
- URI 수정, 필터된 식당리스트뷰 추가, 리뷰 CRUD 유저 판별 로직 추가 
		 
## 수정 사항들 자세한 내용
- URI restful 하게 수정 (ex. restaurant/9/review 리뷰 추가, restaurant/9/review/142 리뷰 수정및 삭제, /2 식당 상세 정보, /?category=2 중식 카테고리인 식당리스트 출력)
- 필터된 식당리스트뷰 추가 (Q객체 사용해서 참조테이블의 컬럼별 필터구현)
- 리뷰 CRUD 유저 판별 로직 추가 (리뷰 CRUD 불필요한 부분 삭제, 코드 정리, 글을 작성한 유저가 아닐 경우 403에러 출력)

## 기타 질문 및 특이 사항
- 검색후 필터도 적용할 수 있으려면 식당리스트뷰에 필터 이후에 검색기능을 함께 넣으면 될까요?  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

<img width="700" alt="Screen Shot 2021-08-10 at 12 19 54 AM" src="https://user-images.githubusercontent.com/8315252/128731254-fb22181a-50d5-47ec-a63f-d452132a9b86.png">
<img width="705" alt="Screen Shot 2021-08-10 at 12 20 43 AM" src="https://user-images.githubusercontent.com/8315252/128731276-343e5246-d3d0-44c6-a9b3-ec5bb09ce1e5.png">
<img width="706" alt="Screen Shot 2021-08-10 at 12 22 04 AM" src="https://user-images.githubusercontent.com/8315252/128731303-904f9e98-7da4-4795-b9be-40182a7fedd8.png">

2021-08-10 04:03 UTC, lordmyshepherd requested changes

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +            serving_price_id  = request.GET.get("serving_price")
query parameter로 받은 값도 명확하게 만들어주는게 좋습니다~

```suggestion
            category_id       = request.GET.get("categoryId")
            location_id       = request.GET.get("locationId")
            serving_price_id  = request.GET.get("servingPriceId")
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +            q        = Q()
붙여주세요~

```suggestion
            q = Q()
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                q &= Q(serving_price = serving_price_id)
```suggestion
                q &= Q(serving_price_id = serving_price_id)
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                q &= Q(location = location_id)
```suggestion
                q &= Q(location_id = location_id)
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                q &= Q(category = category_id)
명확하게 id값으로 조회하는게 좋습니다.
`category = category_id`는 django에서만 허용되는 문법입니다.

```suggestion
                q &= Q(category_id = category_id)
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +            return JsonResponse({"restaurant" : restaurants}, status=200)
아래와 같이 구조를 바꾸는게 더 명확할 것 같습니다. 다만, restaurant에 해당하는 review를 목록으로 반환하지 않고 하나만 반환하는 이유가 뭔가요?
```suggestion
            restaurants = [{
                "id"          : restaurant.id,
                "name"        : restaurant.name,
                "image"       : restaurant.review_set.get(restaurant_id=restaurant.id).reviewimage_set.last().image,
                "rating"      : restaurant.review_set.all().aggregate(rating = Avg('rating'))['rating'],
                "address"     : restaurant.address,
                "is_wished"   : restaurant.wishlist_set.exists(),
                "btn_toggle"  : False,
                "review" : {
                    "id"          : restaurant.review_set.all().order_by('-created_at')[0].id,
                    "user_id"     : restaurant.review_set.all().order_by('-created_at')[0].user_id,
                    "user_name"   : restaurant.review_set.all().order_by('-created_at')[0].user.nickname,
                    "description" : restaurant.review_set.all().order_by('-created_at')[0].description
                }   
            } for restaurant in Restaurant.objects.filter(q).order_by('name')]
            return JsonResponse({"restaurant" : restaurants}, status=200)
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                "restaurant_img" : reviews.last().reviewimage_set.last().image,
이미지를 한장만 반환하는 이유는 뭔가요?

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                                    } for menu in menus],
```suggestion
                "menus" : [{   
                    "item"       : menu.item, 
                    "item_price" : menu.item_price
                } for menu in menus],
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                } for review in reviews]
리뷰 목록을 반환하므로 `reviews`로 key 값을 수정해주세요~
```suggestion
                "reviews"         : [{
                    "id"  : review.id,
                    "user" : {
                        "id" : review.user.id,
                        "name"  : review.user.nickname,
                    },
                    "description": review.description,
                    "rating"     : review.rating,
                    "created_at" : review.created_at,
                    "images url" : review.reviewimage_set.last().image,
                } for review in restaurant.review_set.all()]
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +            rating_num         = restaurant.review_set.all().aggregate(rating = Avg('rating'))['rating']
아래에서 여러번 사용되는 값들이 아니기 때문에 `restaurant`를 제외하고는 아래에서 직접 사용하는게 좋습니다.

```suggestion
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                                    } for menu in menus],
인덴트 맞춰주세요~

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                } for review in reviews]
인덴트도 맞춰주세요!

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +                "is_wished"      : is_wished,
```suggestion
                "is_wished"      : restaurant.wishlist_set.exists(),
```

2021-08-10 04:03 UTC, lordmyshepherd commented on restaurants/views.py
> +            restaurant         = Restaurant.objects.get(id = restaurant_id)
`get()` 함수를 호출할 때, 매칭되는 데이터가 존재하지 않을 경우는 어떻게 되는지 고민해보시면 좋을 것 같습니다.

2021-08-10 04:26 UTC, lunayyko commented on restaurants/views.py
> +            restaurant         = Restaurant.objects.get(id = restaurant_id)
존재하지 않으면 404에러 출력하는 구문 추가했습니다!

2021-08-10 04:29 UTC, lunayyko commented on restaurants/views.py
> +            rating_num         = restaurant.review_set.all().aggregate(rating = Avg('rating'))['rating']
넵 레스토랑만 남기고 삭제했습니다

2021-08-10 04:29 UTC, lunayyko commented on restaurants/views.py
> +                q &= Q(category = category_id)
넵

2021-08-11 05:55 UTC, Kang-kyunghun requested changes

2021-08-11 05:55 UTC, Kang-kyunghun commented on db_uploader.py
> +import os
up_loader 파일은 gitignore에 추가하고 PR에서 제거해 주세요.

2021-08-11 05:55 UTC, Kang-kyunghun commented on users/utils.py
> +            request.user    = User.objects.get(id = user['id'])
= 기준으로 정렬해 주세요.

2021-08-11 05:55 UTC, Kang-kyunghun commented on users/utils.py
> +            print(request.user)
print 제거해 주세요.

2021-08-11 05:55 UTC, Kang-kyunghun commented on restaurants/views.py
> +            results = []
상세 정보 1개를 보내주기 때문에 list에 안 담아도 될 것 같은데 list에 담은 이유가 있나요?

2021-08-11 06:18 UTC, lunayyko commented on restaurants/views.py
> +            results = []
result={}으로 수정했습니다

2021-08-11 06:18 UTC, lunayyko commented on users/utils.py
> +            print(request.user)
넵

2021-08-11 06:18 UTC, lunayyko commented on users/utils.py
> +            request.user    = User.objects.get(id = user['id'])
넵

2021-08-12 01:37 UTC, kst6294 requested changes

2021-08-12 01:37 UTC, kst6294 commented on db_uploader.py
> +import django
여전히 올라가 있습니다! 확인해주세요!

2021-08-12 01:37 UTC, kst6294 commented on restaurants/views.py
> +                    "btn_toggle"     : False,
항상 false 인가요?

2021-08-12 01:37 UTC, kst6294 commented on restaurants/urls.py
> +    # path("", MainView.as_view())
주석제거해주세요.

2021-08-12 01:37 UTC, kst6294 commented on restaurants/urls.py
> +    path("restaurant/<int:restaurant_id>", RestaurantDetailView.as_view()),
restaurant/restaurant/1 
엔드포인트가 이렇게 되나요?

2021-08-12 01:47 UTC, lunayyko commented on restaurants/views.py
> +                    "btn_toggle"     : False,
넵 프론트에서 사용할 수 있게 키값을 넣어달라고 한 토글이라 항상 false입니다

2021-08-12 01:48 UTC, lunayyko commented on restaurants/urls.py
> +    # path("", MainView.as_view())
넵

2021-08-12 01:51 UTC, lunayyko commented on db_uploader.py
> +import django
네 깃헙 브라우저에서 삭제하고 풀했습니다

2021-08-12 01:53 UTC, lunayyko commented on restaurants/urls.py
> +    path("restaurant/<int:restaurant_id>", RestaurantDetailView.as_view()),
바깥 url이 이렇게 되어있어서 
```
urlpatterns = [
    path("",include("restaurants.urls")),
    path("restaurant",include("reviews.urls")),
]
```
아래처럼 되도록 유도했습니다.
*레스토랑 상세정보
restaurant/2
*리뷰 쓸 때
restaurant/2/review
*리뷰 수정 삭제할 때 
restaurant/2/review/144

2021-08-12 04:44 UTC, kst6294 commented
conflict 해결해주세요

2021-08-12 05:01 UTC, lunayyko commented
> conflict 해결해주세요

해결했습니다~! 순태님 감사합니다~!!!

2021-08-12 08:12 UTC, merged